import pandas as pd
import ta
import logging

logger = logging.getLogger(__name__)

class FeatureEngineer:
    @staticmethod
    def add_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate and add technical indicators to the dataframe.
        """
        if df.empty or len(df) < 20:
            logger.warning("DataFrame too small for indicator calculation")
            return df

        try:
            # Momentum Indicators (Expanded)
            df["rsi"] = ta.momentum.RSIIndicator(df["close"]).rsi()
            stoch = ta.momentum.StochasticOscillator(df["high"], df["low"], df["close"])
            df["stoch_k"] = stoch.stoch()
            df["stoch_d"] = stoch.stoch_signal()
            df["williams_r"] = ta.momentum.WilliamsRIndicator(df["high"], df["low"], df["close"]).williams_r()
            
            # Trend Indicators (Expanded)
            df["macd"] = ta.trend.MACD(df["close"]).macd()
            df["macd_signal"] = ta.trend.MACD(df["close"]).macd_signal()
            df["ema_9"] = ta.trend.EMAIndicator(df["close"], window=9).ema_indicator()
            df["ema_21"] = ta.trend.EMAIndicator(df["close"], window=21).ema_indicator()
            df["ema_50"] = ta.trend.EMAIndicator(df["close"], window=50).ema_indicator()
            df["ema_200"] = ta.trend.EMAIndicator(df["close"], window=200).ema_indicator()
            
            adx = ta.trend.ADXIndicator(df["high"], df["low"], df["close"])
            df["adx"] = adx.adx()
            df["cci"] = ta.trend.CCIIndicator(df["high"], df["low"], df["close"]).cci()
            
            # Volatility Indicators
            df["atr"] = ta.volatility.AverageTrueRange(df["high"], df["low"], df["close"]).average_true_range()
            bb = ta.volatility.BollingerBands(df["close"])
            df["bb_high"] = bb.bollinger_hband()
            df["bb_low"] = bb.bollinger_lband()
            
            # Volume Indicators (Expanded)
            df["vwap"] = ta.volume.VolumeWeightedAveragePrice(df["high"], df["low"], df["close"], df["volume"]).volume_weighted_average_price()
            df["obv"] = ta.volume.OnBalanceVolumeIndicator(df["close"], df["volume"]).on_balance_volume()
            
            # Structural Features
            df["dist_to_ema50"] = (df["close"] - df["ema_50"]) / df["ema_50"]
            df["rolling_high_20"] = df["high"].rolling(window=20).max()
            df["rolling_low_20"] = df["low"].rolling(window=20).min()
            
            # Higher High, Lower Low Flags
            df['is_hh'] = df['high'] >= df['rolling_high_20'].shift(1)
            df['is_ll'] = df['low'] <= df['rolling_low_20'].shift(1)
            
            # Drop NaN values generated by windows (optional, here we keep them and handle elsewhere)
            # df.dropna(inplace=True)
            
            return df
        except Exception as e:
            logger.error(f"Error calculating indicators: {e}")
            return df

if __name__ == "__main__":
    # Test with dummy data
    import numpy as np
    data = {
        "open": np.random.randn(250),
        "high": np.random.randn(250) + 1,
        "low": np.random.randn(250) - 1,
        "close": np.random.randn(250),
        "volume": np.random.randint(1000, 5000, 250)
    }
    df = pd.DataFrame(data)
    fe = FeatureEngineer()
    df_with_indicators = fe.add_technical_indicators(df)
    print("Indicators added. Columns:")
    print(df_with_indicators.columns)
    print(df_with_indicators.tail())
